### ISSUE TITLE
Calendar seems to ignore the "Resources" defined in configuration file for RecycleApp 

### ISSUE THREAD

**Issue by Robbe-B** [pippyn/Home-Assistant-Sensor-Afvalbeheer#371]
The calendar seems to get filled with events for resources that aren't there in the configuration. 
For me specific, I'm not interested in the 'gft' events, only 'restafval', 'papier' and 'pmd'.
You'll see that I only specified these resources in the configuration file.
However, when I look at calendar inside home assistant, I've noticed the 'gft' events are also there (see screenshot).

My config: 
![image](https://user-images.githubusercontent.com/103053873/210757038-71e49772-e50e-4262-a2d3-46305962c863.png)

My calendar: 
![image](https://user-images.githubusercontent.com/103053873/210758193-99be23b9-ce00-426a-99fc-5c80b4942870.png)

My instance version:
![image](https://user-images.githubusercontent.com/103053873/210783518-e4bf791b-5517-4fc1-ab89-54526401df39.png)

**Comment by pippyn** [comment]
Any errors in your logs?

**Comment by Robbe-B** [comment]
Only this 
![image](https://user-images.githubusercontent.com/103053873/212903411-ca80a06a-e8e5-48b7-9a9b-7c8a2151ae68.png)

**Comment by Robbe-B** [comment]
Any update on this issue ? 
I've noticed that each sensors that are being created for resources listed in the config, this is correct. (no GFT sensor)
It seems to only happen for the calendar events (GFT events created)
![image](https://user-images.githubusercontent.com/103053873/214540874-5cf34ada-ca7f-4c50-9a1e-6a68e2c945ec.png)

**Comment by pippyn** [comment]
I'm sorry, I totally forgot about this issue.
It is fixed in v5.0.12

**Comment by Robbe-B** [comment]
Thanks, I've just updated to v5.0.12, the GFT events are still in the calendar. I have no clue if these are old events or I should refresh it in some way ?

**Comment by pippyn** [comment]
Maybe you'll need to disable the platform and reboot HA. And enable is again

**Comment by Robbe-B** [comment]
I completly removed the integration, restarted HA, installed the integration again , restarted HA again.
But the GFT events are back in my calendar, it seems this issue is still present in the current version

**Comment by Robbe-B** [comment]
Is this a version issue ? Because v5.0.11 and v5.0.12 are identical :)
![image](https://user-images.githubusercontent.com/103053873/214571009-8779a599-0180-4a50-a729-668a637a2353.png)

**Comment by pippyn** [comment]
uhhh.. I may have forgot to push the changes before drafting a new release...
I'm so sorry😅

v5.0.13 has the bug fix.

**Comment by Robbe-B** [comment]
No problem, I've updated to v5.0.13 and can confirm this issue is solved ! Thanks @pippyn !
